### ISSUE TITLE
Troubles with opencv

### ISSUE THREAD

**Issue by TheYibster** [TheYibster/ASLtranslator#7]
The Camera only takes a frame. Needs the camera app to continually take the frames of the user's camera.

**Comment by Harry262530** [comment]
hello @TheYibster 
if you have used 
if cv.waitKey(0) &0xFF: #== ord('q'):
        break

then change it to
if cv.waitKey(1) &0xFF: #== ord('q'):
        break

because if you input 0 in cn.waitkey it will wait forever

**Comment by TheYibster** [comment]
Thank you so much!
